name: Foreign architectures

on: [push, pull_request]

jobs:
  multiarch:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch: ["armv6", "armv7", "aarch64", "s390x", "ppc64le"]
    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Build and test
      uses: uraimo/run-on-arch-action@v2.1.1
      id: runcmd
      with:
        arch: ${{ matrix.arch }}
        distro: bullseye
        githubToken: ${{ github.token }}
        install: |
          apt update
          apt -qy --no-install-recommends install \
                automake \
                build-essential \
                cmake \
                git \
                libcunit1-dev \
                ninja-build \
                pkg-config \
                unzip \
                wget \
                ;
        run: |
          # Mark submodule as safe directory to prevent error because of code
          # getting built by root (inside QEMU) but checked out by a non-root
          # user (host system).
          git config --global --add safe.directory "${PWD}/examples/shared/tinydtls"

          tools/ci/run_ci.sh --run-build --run-tests
