name: SonarCloud

on: [push]

jobs:
  sonarcloud:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies from APT repository
      run:  |
        sudo apt-get update
        sudo apt-get install gcovr libcunit1-dev wget unzip

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup SonarScanner
      uses: warchant/setup-sonar-scanner@v3
      with:
        version: 4.6.0.2311

    - name: Install Build Wrapper
      run: |
        wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip -O /tmp/build-wrapper-linux-x86.zip
        mkdir ~/opt/
        unzip /tmp/build-wrapper-linux-x86.zip -d ~/opt/

    - name: Collect test coverage data
      run: |
        tools/ci/run_ci.sh \
        --run-build \
        --run-tests \
        --sonarqube ~/opt/build-wrapper-linux-x86/build-wrapper-linux-x86-64

    - name: Run SonarCloud Scan
      run: |
          sonar-scanner \
          -Dsonar.branch.name="${GITHUB_REF_NAME}" \
          -Dsonar.cfamily.build-wrapper-output=build-wakaama/sonar-cloud-build-wrapper-output \
          -Dsonar.cfamily.cache.enabled=false \
          -Dsonar.cfamily.gcov.reportsPath=build-wakaama \
          -Dsonar.cfamily.threads=2 \
          -Dsonar.exclusions="build-wakaama-*/**, .git/**" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.organization=${{ github.repository_owner }} \
          -Dsonar.projectKey="$(echo ${{ github.repository }} | tr / _)" \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.sources=.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
